site_name: Vintage Reel Service Guides
site_url: https://john-tech-writer.github.io/vintage-reel-service-guides

nav:
  - Home: index.md
  - About: about.md

  - Reels - Overviews and Service:
      - Penn:
          - Penn 720 Overview (Spinning): penn/penn-720-overview.md
          - Penn 720 Service (Spinning): penn/penn-720-service-guide.md
      - Pflueger:
          - Pflueger Nobby 1963 Overview (Baitcasting): pflueger/pflueger-nobby-1963-overview.md
          - Pflueger Nobby 1963 Service (Baitcasting): pflueger/pflueger-nobby-service-guide.md
          - Pflueger Pelican 1021 Overview (Spinning): pflueger/pflueger-pelican-1021-overview.md
          - Pflueger Pelican 1021 Service (Spinning): pflueger/pflueger-pelican-1021-service-guide.md
      - Shakespeare:
          - Shakespeare Silent Tru-arT Overview (Fly): shakespeare/shakespeare-silent-tru-art-overview.md
          - Shakespeare Silent Tru-arT Service (Fly): shakespeare/shakespeare-silent-tru-art-service-guide.md
      - Zebco:
          - Zebco 33 Overview (Spincast): zebco/zebco-33-overview.md
          - Zebco 33 Service (Spincast): zebco/zebco-33-service-guide.md

  - General Servicing Information:
      - Workspace Setup and Safety: workspace-setup.md
      - Tools and Materials: tools-materials.md
      - Initial Evaluation: initial-evaluation.md
      - Removing and Adding Line: removing-adding-line.md
      - Epoxy Repairs: epoxy-repairs.md
      - Schematics: schematics.md

  - Background - Reel Types and Makers:
      - A Family Tree of Mid-Century Reels: reel-family-tree.md
      - Baitcasting Reels: baitcasting-reels.md
      - Spinning and Spincast Reels: spinning-reels.md
      - Fly Reels: fly-reels.md
theme:
  name: readthedocs
plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid









